// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2lmTDQnGTcaqnA4L209uWwnONU13qtbE',
    appId: '1:630868221643:web:9e46f931ddb59ce370054e',
    messagingSenderId: '630868221643',
    projectId: 'takao35-app',
    authDomain: 'takao35-app.firebaseapp.com',
    storageBucket: 'takao35-app.firebasestorage.app',
    measurementId: 'G-GJVXXR30P9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0gIL8sOPb1VpiM6mMUGqd_FL0-m_UeEo',
    appId: '1:630868221643:android:7e8ccaadd564432370054e',
    messagingSenderId: '630868221643',
    projectId: 'takao35-app',
    storageBucket: 'takao35-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLP2MTZ2anMXW7z1mxc3aU7J0qUcFp1c8',
    appId: '1:630868221643:ios:b73977766672c1e770054e',
    messagingSenderId: '630868221643',
    projectId: 'takao35-app',
    storageBucket: 'takao35-app.firebasestorage.app',
    iosBundleId: 'com.example.takao35App',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLP2MTZ2anMXW7z1mxc3aU7J0qUcFp1c8',
    appId: '1:630868221643:ios:b73977766672c1e770054e',
    messagingSenderId: '630868221643',
    projectId: 'takao35-app',
    storageBucket: 'takao35-app.firebasestorage.app',
    iosBundleId: 'com.example.takao35App',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2lmTDQnGTcaqnA4L209uWwnONU13qtbE',
    appId: '1:630868221643:web:6087301ce67eb64570054e',
    messagingSenderId: '630868221643',
    projectId: 'takao35-app',
    authDomain: 'takao35-app.firebaseapp.com',
    storageBucket: 'takao35-app.firebasestorage.app',
    measurementId: 'G-8WWPP48Z3D',
  );
}
